//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV.CrescentCove.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV.CrescentCove.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0adventurerADV30Adventurer0
        ///1gladiatorGLA30Gladiator1
        ///2pugilistPGL30Pugilist2
        ///3marauderMRD30Marauder1
        ///4lancerLNC30Lancer2
        ///5archerARC30Archer3
        ///6conjurerCNJ31Conjurer4
        ///7thaumaturgeTHM31Thaumaturge3
        ///8carpenterCRP33Carpenter0
        ///9blacksmithBSM33Blacksmith0
        ///10armorerARM33Armorer0
        ///11goldsmithGSM33Goldsmith0
        ///12leatherworkerLTW33Leatherworker0
        ///13weaverWVR33Weaver0
        ///14alchemistALC33Alchemist0
        ///15culinarianCUL33Culinarian0
        ///16m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassJob {
            get {
                return ResourceManager.GetString("ClassJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00False
        ///1169False
        ///2164False
        ///3161False
        ///4157False
        ///5172False
        ///6166False
        ///7162False
        ///8158False
        ///9163False
        ///10159False
        ///11168False
        ///12170False
        ///13171False
        ///14167False
        ///15217False
        ///16224False
        ///17160False
        ///18349False
        ///19350False
        ///20362False
        ///21360False
        ///22363False
        ///23361False
        ///24373False
        ///25365False
        ///26367False
        ///27371False
        ///28387False
        ///29189False
        ///30188False
        ///31416False
        ///32150False
        ///33420False
        ///34421False
        ///35430False
        ///36434False
        ///37441 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentFinderCondition {
            get {
                return ResourceManager.GetString("ContentFinderCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1gilgilGilTrueFalse
        ///2fire shardfire shardsFire ShardTrueFalse
        ///3ice shardice shardsIce ShardTrueFalse
        ///4wind shardwind shardsWind ShardTrueFalse
        ///5earth shardearth shardsEarth ShardTrueFalse
        ///6lightning shardlightning shardsLightning ShardTrueFalse
        ///7water shardwater shardsWater ShardTrueFalse
        ///8fire crystalfire crystalsFire CrystalTrueFalse
        ///9ice crystalice crystalsIce CrystalTrueFalse
        ///10wind crystalwind crystalsWind CrystalTrueFalse
        ///11earth crystalear [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000
        ///101
        ///20132
        ///30133
        ///40148
        ///50152
        ///60153
        ///70154
        ///80164
        ///90169
        ///100728
        ///110128
        ///120129
        ///130130
        ///14373131
        ///150134
        ///160135
        ///170137
        ///180138
        ///190139
        ///200140
        ///210141
        ///220145
        ///230146
        ///240147
        ///250156
        ///260177
        ///270178
        ///280179
        ///29022
        ///300180
        ///310157
        ///320159
        ///330206
        ///34849161
        ///350202
        ///360207
        ///370168
        ///380172
        ///390208
        ///40850161
        ///41372161
        ///42854163
        ///43855163
        ///44856163
        ///450158
        ///460162
        ///470217
        ///48599166
        ///49873167
        ///5092217 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18Levemete
        ///19
        ///20Hydaelyn
        ///21Eorzea
        ///22La Noscea
        ///23The Black Shroud
        ///24Thanalan
        ///25Coerthas
        ///26Mor Dhona
        ///27Limsa Lominsa
        ///28Limsa Lominsa Upper Decks
        ///29Limsa Lominsa Lower Decks
        ///30Middle La Noscea
        ///31Lower La Noscea
        ///32Eastern La Noscea
        ///33Western La Noscea
        ///34Upper La Noscea
        ///35Sastasha
        ///36Brayflox&apos;s Longstop
        ///37The Wanderer&apos;s Palace
        ///38
        ///39Gridania
        ///40Ul&apos;dah - Steps of Nald
        ///41Ul&apos;dah - Steps of Tha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlaceName {
            get {
                return ResourceManager.GetString("PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000
        ///20000
        ///30000
        ///40000
        ///50000
        ///60000
        ///70000
        ///80000
        ///90000
        ///100000
        ///110000
        ///130000
        ///140000
        ///150000
        ///160000
        ///170000
        ///180000
        ///190000
        ///200000
        ///210000
        ///220000
        ///240000
        ///250000
        ///260000
        ///270000
        ///280000
        ///290000
        ///128225002811
        ///129225002912
        ///130245044013
        ///131245044114
        ///13223506522
        ///13323506533
        ///134225023015
        ///135225023116
        ///1362250242572
        ///137225023217
        ///138225023318
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TerritoryType {
            get {
                return ResourceManager.GetString("TerritoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23Asura
        ///24Belias
        ///25Chaos
        ///26Hecatoncheir
        ///27Moomba
        ///28Pandaemonium
        ///29Shinryu
        ///30Unicorn
        ///31Yojimbo
        ///32Zeromus
        ///33Twintania
        ///34Brynhildr
        ///35Famfrit
        ///36Lich
        ///37Mateus
        ///38Shemhazai
        ///39Omega
        ///40Jenova
        ///41Zalera
        ///42Zodiark
        ///43Alexander
        ///44Anima
        ///45Carbuncle
        ///46Fenrir
        ///47Hades
        ///48Ixion
        ///49Kujata
        ///50Typhon
        ///51Ultima
        ///52Valefor
        ///53Exodus
        ///54Faerie
        ///55Lamia
        ///56Phoenix
        ///57Siren
        ///58Garuda
        ///59Ifrit
        ///60Ramuh
        ///61Titan
        ///62Diabolos
        ///63Gilgamesh
        ///64Leviathan
        ///65Midgardsormr
        ///66 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
