//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrescentCove.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrescentCove.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0adventurerADV30Adventurer0
        ///1gladiatorGLA30Gladiator1
        ///2pugilistPGL30Pugilist2
        ///3marauderMRD30Marauder1
        ///4lancerLNC30Lancer2
        ///5archerARC30Archer3
        ///6conjurerCNJ31Conjurer4
        ///7thaumaturgeTHM31Thaumaturge3
        ///8carpenterCRP33Carpenter0
        ///9blacksmithBSM33Blacksmith0
        ///10armorerARM33Armorer0
        ///11goldsmithGSM33Goldsmith0
        ///12leatherworkerLTW33Leatherworker0
        ///13weaverWVR33Weaver0
        ///14alchemistALC33Alchemist0
        ///15culinarianCUL33Culinarian0
        ///16m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassJob {
            get {
                return ResourceManager.GetString("ClassJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00False
        ///1169False
        ///2164False
        ///3161False
        ///4157False
        ///5172False
        ///6166False
        ///7162False
        ///8158False
        ///9163False
        ///10159False
        ///11168False
        ///12170False
        ///13171False
        ///14167False
        ///15217False
        ///16224False
        ///17160False
        ///18349False
        ///19350False
        ///20362False
        ///21360False
        ///22363False
        ///23361False
        ///24373False
        ///25365False
        ///26367False
        ///27371False
        ///28387False
        ///29189False
        ///30188False
        ///31416False
        ///32150False
        ///33420False
        ///34421False
        ///35430False
        ///36434False
        ///37441 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentFinderCondition {
            get {
                return ResourceManager.GetString("ContentFinderCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1gilgilGilTrueFalse
        ///2fire shardfire shardsFire ShardTrueFalse
        ///3ice shardice shardsIce ShardTrueFalse
        ///4wind shardwind shardsWind ShardTrueFalse
        ///5earth shardearth shardsEarth ShardTrueFalse
        ///6lightning shardlightning shardsLightning ShardTrueFalse
        ///7water shardwater shardsWater ShardTrueFalse
        ///8fire crystalfire crystalsFire CrystalTrueFalse
        ///9ice crystalice crystalsIce CrystalTrueFalse
        ///10wind crystalwind crystalsWind CrystalTrueFalse
        ///11earth crystalear [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23Asura
        ///24Belias
        ///25Chaos
        ///26Hecatoncheir
        ///27Moomba
        ///28Pandaemonium
        ///29Shinryu
        ///30Unicorn
        ///31Yojimbo
        ///32Zeromus
        ///33Twintania
        ///34Brynhildr
        ///35Famfrit
        ///36Lich
        ///37Mateus
        ///38Shemhazai
        ///39Omega
        ///40Jenova
        ///41Zalera
        ///42Zodiark
        ///43Alexander
        ///44Anima
        ///45Carbuncle
        ///46Fenrir
        ///47Hades
        ///48Ixion
        ///49Kujata
        ///50Typhon
        ///51Ultima
        ///52Valefor
        ///53Exodus
        ///54Faerie
        ///55Lamia
        ///56Phoenix
        ///57Siren
        ///58Garuda
        ///59Ifrit
        ///60Ramuh
        ///61Titan
        ///62Diabolos
        ///63Gilgamesh
        ///64Leviathan
        ///65Midgardsormr
        ///66 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
